name: bebesarah
favicon: null
layout_spectrum: 0.6677271944936365
typography_spectrum: 0.48700311849825084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1282593128271401
  lightness: 0.6502762222662568
  saturation: 0.39305652654729784
  rhythmicContrast: 0.4049337152391672
purpose: []
